# Site settings
title: Whatever You Want
email: kelly.kim19951110@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  https://kellykim1110.github.io/ # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
github_username:  kellykim1110

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

